### ISSUE TITLE
大佬，运行get id报错这个怎么回事啊

### ISSUE THREAD

**Issue by yongjie9** [System233/time-helper#1]
Run npm install
added 49 packages from 129 contributors and audited 50 packages in 2.988s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> time-helper@1.0.0 appId /home/runner/work/time-helper/time-helper
> npx ts-node tools/appId.ts

npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! time-helper@1.0.0 appId: `npx ts-node tools/appId.ts`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the time-helper@1.0.0 appId script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-12-22T15_51_16_701Z-debug.log

**Comment by System233** [comment]
看一下手机上的错误通知，在配置了SCKEY的情况下，错误信息不会显示在Actions里

**Comment by yongjie9** [comment]
TypeError: Cannot read property 'slice' of undefined
    at Object.getAppIdFromUrl (/home/runner/work/time-helper/time-helper/src/utils.ts:13:22)
    at /home/runner/work/time-helper/time-helper/tools/appId.ts:18:46
    at Array.map ()
    at /home/runner/work/time-helper/time-helper/tools/appId.ts:18:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by System233** [comment]
看来是从URL获取id参数的时候，服务器返回的数据中缺少字段。
你的学校有没有多个打卡项目？比如不同年级有各自的打卡选项？
若可以的话希望可以提供更多信息进行测试，敏感信息通过邮箱交流dark.matter@foxmail.com

**Comment by chen135259** [comment]
Cannot read property 'deptid' of null
```js
TypeError: Cannot read property 'deptid' of null
    at Helper.run (/root/workspace/time-helper/dist/src/helper.js:118:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.main (/root/workspace/time-helper/dist/tools/index.js:59:22)
```
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! time-helper@1.1.1 main: `node dist/tools/main.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the time-helper@1.1.1 main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by chen135259** [comment]
我的也是报错这个

**Comment by System233** [comment]
> Cannot read property 'deptid' of null
> 
> ```js
> TypeError: Cannot read property 'deptid' of null
>     at Helper.run (/root/workspace/time-helper/dist/src/helper.js:118:29)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async Object.main (/root/workspace/time-helper/dist/tools/index.js:59:22)
> ```
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 255
> npm ERR! time-helper@1.1.1 main: `node dist/tools/main.js`
> npm ERR! Exit status 255
> npm ERR!
> npm ERR! Failed at the time-helper@1.1.1 main script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

你这个的情况又不一样，我记得`deptid`是系部ID，获取不到可能是打卡前没有填个人信息导致的。  
你要先正常打一次卡，然后才能用程序打卡。
如果问题依旧，那就得抓包才知道是什么原因了。
