### ISSUE TITLE
位置获取问题

### ISSUE THREAD

**Issue by bakeham** [System233/time-helper#10]
在部署到scf上的打卡结果显示，打卡位置为（学校）
不知道获取位置的逻辑是怎样的？
为何他使用了很早以前的位置信息，而不是上次打卡的位置信息

**Comment by System233** [comment]
如果没有设置`LOCATION`参数，则直接复制获取的上次位置信息。

**Comment by bakeham** [comment]
那是否可以使用手机打卡后，重新部署项目来解决呢

**Comment by bakeham** [comment]
指定location参数后仍然被定位至学校

**Comment by System233** [comment]
> 指定location参数后仍然被定位至学校

`LOCATION`配置有误时，参数不会生效   
参数的格式是`经度,纬度,半径`

**Comment by bakeham** [comment]
> > 指定location参数后仍然被定位至学校
> 
> `LOCATION`配置有误时，参数不会生效
> 参数的格式是`经度,纬度,半径`

位置似乎无误，我直接复制了百度坐标拾取器的经纬度，半径可选就没填写

**Comment by bakeham** [comment]
> > 指定location参数后仍然被定位至学校
> 
> `LOCATION`配置有误时，参数不会生效
> 参数的格式是`经度,纬度,半径`

配置半径后仍然无法正确定位

**Comment by System233** [comment]
> > > 指定location参数后仍然被定位至学校
> > 
> > 
> > `LOCATION`配置有误时，参数不会生效
> > 参数的格式是`经度,纬度,半径`
> 
> 位置似乎无误，我直接复制了百度坐标拾取器的经纬度，半径可选就没填写

没道理会这样，如果设置了位置，那位置信息就会按着设置的来，这部分逻辑是跟打卡无关的。
百度定位给出的地点名称会有一些偏差，但也不会差太多

**Comment by System233** [comment]
你可以本地调试打个断点或者log一下看看是怎么跑的

**Comment by bakeham** [comment]
scf运行日志如下，希望可以获得您的帮助，谢谢 :-) 
：
```
START RequestId: 30d19942-844d-43af-b3cc-3d8d273d1ead

Event RequestId: 30d19942-844d-43af-b3cc-3d8d273d1ead

B1%85%E4%BD%8F%E5%AE%B6%E5%BA%AD%E6%88%90%E5%91%98%E4%B8%AD%E6%98%AF%E5%90%A6%E6%9C%89%E7%B1%BB%E5%9E%8B%E4%BB%A5%E4%B8%8B%E6%83%85%E5%86%B5%EF%BC%9F%7C%E5%90%A6%20%20%0A%E5%B1%85%E6%B0%91%E5%81%A5%E5%BA%B7%E7%A0%81%E9%A2%9C%E8%89%B2%7C%E7%BB%BF%E8%89%B2%20%20%0A%E6%9C%AC%E4%BA%BA%E7%94%B5%E8%AF%9D%7C17773341668%20%20%0A%E7%B4%A7%E6%80%A5%E8%81%94%E7%B3%BB%E4%BA%BA%E5%A7%93%E5%90%8D%7C%E6%9D%8E%E5%8B%87%20%20%0A%E7%B4%A7%E6%80%A5%E8%81%94%E7%B3%BB%E4%BA%BA%E6%89%8B%E6%9C%BA%E5%8F%B7%7C13171227466%20%20%0A%E6%82%A8%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E5%AD%A6%E6%A0%A1%E6%8F%90%E4%BE%9B%E8%B7%9F%E6%AD%A4%E6%AC%A1%E7%96%AB%E6%83%85%E7%9B%B8%E5%85%B3%E7%9A%84%E5%8D%8F%E5%8A%A9%EF%BC%9F%E5%A6%82%E6%9C%89%EF%BC%8C%E8%AF%B7%E5%85%B7%E4%BD%93%E8%AF%B4%E6%98%8E%EF%BC%9A%7C%20%20%0A',

      headers: [Object],

      transformRequest: [Array],

      transformResponse: [Array],

      timeout: 0,

      adapter: [Function: httpAdapter],

      xsrfCookieName: 'XSRF-TOKEN',

      xsrfHeaderName: 'X-XSRF-TOKEN',

      maxContentLength: -1,

      maxBodyLength: -1,

      validateStatus: [Function: validateStatus]

    },

    request: ClientRequest {

      _events: [Object: null prototype],

      _eventsCount: 7,

      _maxListeners: undefined,

      outputData: [],

      outputSize: 0,

      writable: true,

      _last: true,

      chunkedEncoding: false,

      shouldKeepAlive: false,

      useChunkedEncodingByDefault: true,

      sendDate: false,

      _removedConnection: false,

      _removedContLen: false,

      _removedTE: false,

      _contentLength: null,

      _hasBody: true,

      _trailer: '',

      finished: true,

      _headerSent: true,

      socket: [TLSSocket],

      connection: [TLSSocket],

      _header: 'POST /SCU107210T216446c6649317a1dea6df9a98094b325f1d5a79297d7.send HTTP/1.1\r\n' +

        'Accept: application/json, text/plain, */*\r\n' +

        'Content-Type: application/x-www-form-urlencoded\r\n' +

        'User-Agent: axios/0.21.1\r\n' +

        'Content-Length: 3601\r\n' +

        'Host: sc.ftqq.com\r\n' +

        'Connection: close\r\n' +

        '\r\n',

      _onPendingData: [Function: noopPendingOutput],

      agent: [Agent],

      socketPath: undefined,

      method: 'POST',

      insecureHTTPParser: undefined,

      path: '/SCU107210T216446c6649317a1dea6df9a98094b325f1d5a79297d7.send',

      _ended: true,

      res: [IncomingMessage],

      aborted: false,

      timeoutCb: null,

      upgradeOrConnect: false,

      parser: null,

      maxHeadersCount: null,

      reusedSocket: false,

      _redirectable: [Writable],

      [Symbol(kCapture)]: false,

      [Symbol(kNeedDrain)]: false,

      [Symbol(corked)]: 0,

      [Symbol(kOutHeaders)]: [Object: null prototype]

    },

    data: `<!DOCTYPE html><html><head><meta charset="utf-8"/><meta name="viewport"content="initial-scale=1.0, user-scalable=no"/><title>609-AFW Block-Sina App Engine</title><link rel="stylesheet"type="text/css"href="//lib.sinaapp.com/l7/b.css"/></head><body><div class="ed"><div class="ec"><img src="//lib.sinaapp.com/l7/error_img.gif"class="fl ei"/><div class="et">您的请求已被防火墙拦截。<br/></div><div class="ex">请参考：<a href="http://news.sinacloud.com/why-609-block/">为什么我的访问出现609？</a></div><div class="ex"id="ip"></div><div class="sinacloud"><a href="https://www.sinacloud.com">新浪云</a></div></div></div></body><script type="text/javascript">document.addEventListener("DOMContentLoaded",function(){var cookie=document.cookie;if(cookie.length){var split_ret=cookie.split(';');var cookie_parsed={};for(var i in split_ret){var tmp_split=split_ret[i].split('=');var left=tmp_split[0].replace(/(^\\s*)/g,"");cookie_parsed[left]=tmp_split[1]}var html='<div class="ex" id="ip">';var push_data=[];if(cookie_parsed['cip']){push_data.push('客户端IP：'+cookie_parsed['cip'])}if(cookie_parsed['saeuuid']){push_data.push('UUID：'+cookie_parsed['saeuuid'])}html+=push_data.join(" ");html+='</div>';document.getElementById('ip').outerHTML=html}});</script></html>\r\n`

  },

  isAxiosError: true,

  toJSON: [Function: toJSON]

}


END RequestId: 30d19942-844d-43af-b3cc-3d8d273d1ead

Report RequestId: 30d19942-844d-43af-b3cc-3d8d273d1ead Duration:1806ms Memory:128MB MemUsage:64.918MB
```

**Comment by bakeham** [comment]
我注意到好像这里没有location参数
![image](https://user-images.githubusercontent.com/49135636/106730625-8aaa6280-6649-11eb-9e8b-2131efd17898.png)

**Comment by System233** [comment]
我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。

**Comment by bakeham** [comment]
> 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。

我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的

**Comment by System233** [comment]
> > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> 
> 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的

上面的报错就是server酱防火墙的提示啊

**Comment by bakeham** [comment]
> > > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> > 
> > 
> > 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的
> 
> 上面的报错就是server酱防火墙的提示啊

奇了怪了，可是sever一切正常呀

**Comment by System233** [comment]
> > > > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> > > 
> > > 
> > > 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的
> > 
> > 
> > 上面的报错就是server酱防火墙的提示啊
> 
> 奇了怪了，可是sever一切正常呀

可能有多个服务器，重新生成下server酱的key。
我用广州的腾讯云服务器是连不上server酱的，报错609

**Comment by bakeham** [comment]
> > > > > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> > > > 
> > > > 
> > > > 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的
> > > 
> > > 
> > > 上面的报错就是server酱防火墙的提示啊
> > 
> > 
> > 奇了怪了，可是sever一切正常呀
> 
> 可能有多个服务器，重新生成下server酱的key。
> 我用广州的腾讯云服务器是连不上server酱的，报错609

哈哈哈应该是的，不是我现在问题是 打卡位置异常嘛，应该sever酱不会影响到吧

**Comment by System233** [comment]
> > > > > > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> > > > > 
> > > > > 
> > > > > 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的
> > > > 
> > > > 
> > > > 上面的报错就是server酱防火墙的提示啊
> > > 
> > > 
> > > 奇了怪了，可是sever一切正常呀
> > 
> > 
> > 可能有多个服务器，重新生成下server酱的key。
> > 我用广州的腾讯云服务器是连不上server酱的，报错609
> 
> 哈哈哈应该是的，不是我现在问题是 打卡位置异常嘛，应该sever酱不会影响到吧

你配了多个服务器，那个服务器不是腾讯云，所以Server酱可以推送成功，同时你设置的位置参数也因为不在那个服务器上所以无效。

**Comment by System233** [comment]
获取位置跟打卡的代码逻辑是无关的，设置位置后，上次打卡的位置不可能会被传过来。

**Comment by System233** [comment]
实在不行，可以在本地配好参数，看看位置会不会跟着参数变。运行正常后，再把参数复制到服务器。

**Comment by bakeham** [comment]
> > > > > > > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> > > > > > 
> > > > > > 
> > > > > > 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的
> > > > > 
> > > > > 
> > > > > 上面的报错就是server酱防火墙的提示啊
> > > > 
> > > > 
> > > > 奇了怪了，可是sever一切正常呀
> > > 
> > > 
> > > 可能有多个服务器，重新生成下server酱的key。
> > > 我用广州的腾讯云服务器是连不上server酱的，报错609
> > 
> > 
> > 哈哈哈应该是的，不是我现在问题是 打卡位置异常嘛，应该sever酱不会影响到吧
> 
> 你配了多个服务器，那个服务器不是腾讯云，所以Server酱可以推送成功，同时你设置的位置参数也因为不在那个服务器上所以无效。

确定是腾讯云，因为我每次点测试都会sever酱推送，环境变量也配在腾讯云里了

**Comment by System233** [comment]
> > > > > > > > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> > > > > > > 
> > > > > > > 
> > > > > > > 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的
> > > > > > 
> > > > > > 
> > > > > > 上面的报错就是server酱防火墙的提示啊
> > > > > 
> > > > > 
> > > > > 奇了怪了，可是sever一切正常呀
> > > > 
> > > > 
> > > > 可能有多个服务器，重新生成下server酱的key。
> > > > 我用广州的腾讯云服务器是连不上server酱的，报错609
> > > 
> > > 
> > > 哈哈哈应该是的，不是我现在问题是 打卡位置异常嘛，应该sever酱不会影响到吧
> > 
> > 
> > 你配了多个服务器，那个服务器不是腾讯云，所以Server酱可以推送成功，同时你设置的位置参数也因为不在那个服务器上所以无效。
> 
> 确定是腾讯云，因为我每次点测试都会sever酱推送，环境变量也配在腾讯云里了

重新生成server酱key，再拉一遍代码

**Comment by bakeham** [comment]
> > > > > > > > > 我看到了Server酱，server酱的防火墙屏蔽了腾讯云，推送不了的，换个其他的推送服务。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我这里sever酱推送一切正常，我查看打卡位置为学校也是从sever酱推送看到的
> > > > > > > 
> > > > > > > 
> > > > > > > 上面的报错就是server酱防火墙的提示啊
> > > > > > 
> > > > > > 
> > > > > > 奇了怪了，可是sever一切正常呀
> > > > > 
> > > > > 
> > > > > 可能有多个服务器，重新生成下server酱的key。
> > > > > 我用广州的腾讯云服务器是连不上server酱的，报错609
> > > > 
> > > > 
> > > > 哈哈哈应该是的，不是我现在问题是 打卡位置异常嘛，应该sever酱不会影响到吧
> > > 
> > > 
> > > 你配了多个服务器，那个服务器不是腾讯云，所以Server酱可以推送成功，同时你设置的位置参数也因为不在那个服务器上所以无效。
> > 
> > 
> > 确定是腾讯云，因为我每次点测试都会sever酱推送，环境变量也配在腾讯云里了
> 
> 重新生成server酱key，再拉一遍代码

明白~

**Comment by bakeham** [comment]
抱歉前段时间忙，今天试了，问题解决！感谢作者的支持！
