### ISSUE TITLE
请问，ip所在地和打卡位置不一样，会不会给封号了

### ISSUE THREAD

**Issue by zzz1999** [System233/time-helper#14]
打卡服务器在上海，结果学校不在上海
这种情况会不会被封号？
暴论：如果用学校的梯子，这样会不会就ojbk了。

**Comment by System233** [comment]
不会,以前国外IP都没事

**Comment by System233** [comment]
这个项目如此坚挺还是挺意外的🤣

**Comment by zzz1999** [comment]
希望能继续更新下去。怡情估计不会结束的很块，可能这个项目还会有很多人用它。我学校里挺多人用的，有些人没自己服务器就用腾讯云测试API整了个每天准点打卡233

**Comment by System233** [comment]
我们现在没有用这个平台打卡了，不太好测试
另外还有一些人是用的git clone机制每天打的卡，所以主分支不能大改
现在的打卡账号机制还是原来github actions的设置环境变量模式，每次运行只能打卡一个账号，比较浪费资源，稍微改改可以做成一次打卡多账号的

**Comment by System233** [comment]
说实话看到有其他项目用了自己逆向出的逻辑却没有署自己名挺失望的，唉~
居然感谢别人不感谢我，属实大无语了😫

**Comment by zzz1999** [comment]
强烈谴责
不哭摸摸头(*╯3╰)
