### ISSUE TITLE
打卡成功率与网络问题

### ISSUE THREAD

**Issue by System233** [System233/time-helper#3]
## ⚡网络问题

Github Action服务器在海外，且每次运行时的机器不一样，有时会遇到网络不通打卡失败的情况。
对此我没有好的解决方案，目前的办法是添加两个运行时间点，每天打两次卡，到现在还没遇过两次打卡都遇到网络问题的情况。
也许可以自己租个服务器做代理，然后添加`PROXY_HOST`跟`PROXY_PORT`参数来提升稳定性，但我觉得这成本太高了，还不如直接在租的服务器上跑。

项目中`Token`令牌登录在action中失败也是由于IP变动的原因，IP变得太厉害，登录就会失效，需要重新登录。

`PROXY_HOST`和`PROXY_PORT`是两个代理参数，最初是用来观察测试数据的，但现在可以用来解决Action中的Token登录和网络问题。

## ✔替代方案

前不久我也收到消息，说对面可能在封海外IP，但我这边一直正常运行，没有发现新的异样。
如果对面真的封IP，那么上述方法是继续使用action的唯一选择，当然咱也可以放弃action，转去薅云函数之类的羊毛。
项目本身是`TypeScript`写的，可以编译为`JS`，只要服务器能跑这两个语言，那么就没问题。虽然当初没有考虑这么多，不过小改一下还是能跑起来的，入口都已经写好了，引入就OK。

届时你可以直接修改[config.ts](../blob/master/src/config.ts)，添加运行参数，反正别人也看不了你代码，云函数启动的时候直接`import "tools/main"`/`require("tools/main")`开始打卡，`import "tools/appId"`/`require("tools/appId")"`获取ID。
你也可以把里面的函数复制出来，自定义个新函数，都是可以的。
另外在部署云函数的时候记得把依赖库也部署上去，缺依赖可跑不起来。

## ☀优化

使用专用的服务器（如云函数）运行脚本时，可以考虑采用token登录，减少登录频率。

## ⚠警告

在Github上跑的时候千万不要往`config.ts`里写配置，别人是看得到的！

**Comment by XHym139** [comment]
在coding上运行能给个教程吗？

**Comment by System233** [comment]
> 在coding上运行能给个教程吗？

加上了 #4 ，你可以试试

实际上那边并没有封IP，只是换了下服务器域名，现在github的action还可以正常使用。

**Comment by XHym139** [comment]
我在获取APP_ID时，server只给我发了一个APP_ID，下面没有任何内容，用命令行获取也获取不了

**Comment by System233** [comment]
> 我在获取APP_ID时，server只给我发了一个APP_ID，下面没有任何内容，用命令行获取也获取不了

手动打卡时是怎么样的？点进去直接就到了填表步骤，还是要选一下打卡项目才填表？
按理只获取到一个id就说明只有一个打卡项目。

**Comment by XHym139** [comment]
手动打卡，进去之后直接就填表，没有APP_ID打卡失败

**Comment by System233** [comment]
> 手动打卡，进去之后直接就填表，没有APP_ID打卡失败

我的有好几个打卡项目，点进去后要先选一下才能填表。
像你这种情况的话，可能是因为只有一个选项，所以就跳过选择了。
你可以试试把那一个Id填进去打卡，过会看看打卡记录里有没有体温数据。

**Comment by XHym139** [comment]
![图片](https://user-images.githubusercontent.com/67096462/105655021-3b05c180-5efa-11eb-8fbf-eeb30e91b2f5.png)
命令获取是这样，
![图片](https://user-images.githubusercontent.com/67096462/105655420-f9294b00-5efa-11eb-8810-75b96abff4f7.png)

**Comment by System233** [comment]
> ![图片](https://user-images.githubusercontent.com/67096462/105655021-3b05c180-5efa-11eb-8fbf-eeb30e91b2f5.png)
> 命令获取是这样，
> ![图片](https://user-images.githubusercontent.com/67096462/105655420-f9294b00-5efa-11eb-8810-75b96abff4f7.png)

第一张是按照 #2 的方法运行出来的么？没有报错说明是登录成功了，但是没有获取到打卡项目。
第二张是没设置运行参数，参数是设置在环境变量里的。

看来跟我的打卡流程不一样，得有账号测试才知道怎么弄了。

**Comment by XHym139** [comment]
加一下qq，私聊，我对这不是很懂，把信息都删了吧，嗯......,行不？

**Comment by System233** [comment]
dark.matter@foxmail.com 邮箱里聊
