### ISSUE TITLE
获取AppID这一步，手机上只有一行：打卡项目APP_ID

### ISSUE THREAD

**Issue by Yehuw** [System233/time-helper#5]

**Comment by System233** [comment]
今晚我看一下能不能解决
有些人的打卡是点进去就填表，没有选择打卡项目这个过程，所以获取出来是空的

**Comment by System233** [comment]
尝试这个ID：pneumonia
点进去直接打卡的可能默认都是这个ID

**Comment by Yehuw** [comment]
可行，我打卡成功了，感谢

**Comment by bakeham** [comment]
![image](https://user-images.githubusercontent.com/49135636/106077140-f2454700-614b-11eb-88a8-fe4438eebdd4.png)
出现AppID空的情况 填入"pneumonia" 亲测可成功
